services:
  DiscContainerController:
    image: thisismynameok/disccontainercontroller:latest
    container_name: DiscContainerController
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock